// Package learn implements `mcp-recall learn` (connect to installed MCP servers,
// introspect tools, generate TOML profiles) and `profiles retrain`. Ports
// src/learn/*.ts.
package learn

import (
	"regexp"
	"strings"
)

// McpTool is a tool schema introspected from an MCP server.
type McpTool struct {
	Name        string
	Description string
	InputProps  []string // input-schema property names, in order
}

var (
	listVerbs   = regexp.MustCompile(`(?i)^(list|search|find|query|get_all|fetch_all)`)
	singleVerbs = regexp.MustCompile(`(?i)^(get|fetch|read|describe|show|retrieve)`)
	writeVerbs  = regexp.MustCompile(`(?i)^(create|update|delete|remove|set|add|post|put|patch)`)
)

var commonFields = []string{"id", "title", "name", "status", "description"}

func lastSegment(toolName string) string {
	parts := strings.Split(toolName, "__")
	return parts[len(parts)-1]
}

// impliesList reports whether a tool likely returns a collection.
func impliesList(toolName, description string) bool {
	base := lastSegment(toolName)
	if listVerbs.MatchString(base) {
		return true
	}
	if writeVerbs.MatchString(base) {
		return false
	}
	if singleVerbs.MatchString(base) {
		return false
	}
	if description != "" {
		d := strings.ToLower(description)
		return strings.Contains(d, "list") || strings.Contains(d, "search") || strings.Contains(d, "results")
	}
	return false
}

var skipInputFields = map[string]bool{
	"limit": true, "cursor": true, "offset": true, "page": true, "query": true, "filter": true,
}

func schemaFields(props []string) []string {
	var out []string
	for _, k := range props {
		if !skipInputFields[k] {
			out = append(out, k)
		}
	}
	return out
}

func suggestItemsPaths(serverKey string, tools []McpTool) []string {
	var names []string
	for _, t := range tools {
		names = append(names, strings.ToLower(t.Name))
	}
	allNames := strings.Join(names, " ")

	keywords := [][2]string{
		{"issue", "issues"}, {"ticket", "tickets"}, {"page", "pages"}, {"item", "items"},
		{"result", "results"}, {"task", "tasks"}, {"record", "records"}, {"node", "nodes"},
		{"message", "messages"},
	}
	var paths []string
	seen := map[string]bool{}
	add := func(p string) {
		if !seen[p] {
			seen[p] = true
			paths = append(paths, p)
		}
	}
	for _, kw := range keywords {
		if strings.Contains(allNames, kw[0]) || strings.Contains(serverKey, kw[0]) {
			add(kw[1])
		}
	}
	for _, fb := range []string{"items", "results", "data", "nodes"} {
		add(fb)
	}
	if len(paths) > 6 {
		paths = paths[:6]
	}
	return paths
}

func dedup(xs []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, x := range xs {
		if !seen[x] {
			seen[x] = true
			out = append(out, x)
		}
	}
	return out
}

// generateProfile builds a TOML profile string from a server's tool schemas.
func generateProfile(serverKey string, tools []McpTool) string {
	norm := strings.ReplaceAll(serverKey, "-", "_")
	id := "mcp__" + norm
	pattern := "mcp__" + norm + "__*"
	toolCount := len(tools)

	var listTools []McpTool
	for _, t := range tools {
		if impliesList(t.Name, t.Description) {
			listTools = append(listTools, t)
		}
	}
	useExtract := len(listTools) > 0

	toolPlural := "s"
	if toolCount == 1 {
		toolPlural = ""
	}
	description := "Auto-generated profile for " + serverKey + " (" + itoa(toolCount) + " tool" + toolPlural + " — run mcp-recall learn to regenerate)"

	if !useExtract {
		var toolBases []string
		for _, t := range tools {
			toolBases = append(toolBases, lastSegment(t.Name))
		}
		return strings.Join([]string{
			"# Generated by: mcp-recall learn",
			"# Tools: " + strings.Join(toolBases, ", "),
			"# Refine strategy.fields after observing real tool output.",
			"",
			"[profile]",
			`id          = "` + id + `"`,
			`version     = "1.0.0"`,
			`description = "` + description + `"`,
			`mcp_pattern = "` + pattern + `"`,
			"",
			"[strategy]",
			`type            = "json_truncate"`,
			"max_depth       = 3",
			"max_array_items = 5",
			"fallback_chars  = 500",
		}, "\n") + "\n"
	}

	var schemaHints []string
	for _, t := range listTools {
		schemaHints = append(schemaHints, schemaFields(t.InputProps)...)
	}
	candidateFields := dedup(append(append([]string{}, commonFields...), schemaHints...))
	if len(candidateFields) > 8 {
		candidateFields = candidateFields[:8]
	}
	itemsPaths := suggestItemsPaths(serverKey, tools)

	var fieldLines, pathLines, listBases []string
	for _, f := range candidateFields {
		fieldLines = append(fieldLines, `  "`+f+`",`)
	}
	for _, p := range itemsPaths {
		pathLines = append(pathLines, `  "`+p+`",`)
	}
	for _, t := range listTools {
		listBases = append(listBases, lastSegment(t.Name))
	}

	return strings.Join([]string{
		"# Generated by: mcp-recall learn",
		"# List tools detected: " + strings.Join(listBases, ", "),
		"# Refine items_path and fields after observing real tool output.",
		"",
		"[profile]",
		`id          = "` + id + `"`,
		`version     = "1.0.0"`,
		`description = "` + description + `"`,
		`mcp_pattern = "` + pattern + `"`,
		"",
		"[strategy]",
		`type = "json_extract"`,
		"items_path = [",
		strings.Join(pathLines, "\n"),
		"]",
		"fields = [",
		strings.Join(fieldLines, "\n"),
		"]",
		"max_items           = 10",
		"max_chars_per_field = 200",
		"fallback_chars      = 500",
	}, "\n") + "\n"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var b []byte
	for n > 0 {
		b = append([]byte{byte('0' + n%10)}, b...)
		n /= 10
	}
	if neg {
		return "-" + string(b)
	}
	return string(b)
}
