// mcprecall-go - Developed by acidvegas in Go (https://github.com/acidvegas)
// internal/learn/generate_port_test.go
//
// Port of tests/learn.test.ts (upstream v1.9.0) granular assertions.

package learn

import (
	"strings"
	"testing"

	"github.com/BurntSushi/toml"
)

func TestImpliesListGranular(t *testing.T) {
	cases := []struct {
		name, desc string
		want       bool
	}{
		{"list_issues", "", true},
		{"mcp__jira__list_issues", "", true},
		{"search_pages", "", true},
		{"find_users", "", true},
		{"get_issue", "", false},
		{"create_issue", "", false},
		{"delete_issue", "", false},
		{"execute", "Returns a list of results", true},
		{"execute", "Runs a command", false},
	}
	for _, c := range cases {
		if got := impliesList(c.name, c.desc); got != c.want {
			t.Errorf("impliesList(%q,%q) = %v, want %v", c.name, c.desc, got, c.want)
		}
	}
}

var listTools = []McpTool{
	{Name: "list_issues", Description: "List Jira issues"},
	{Name: "search_issues", Description: "Search issues"},
	{Name: "get_issue", Description: "Get a single issue"},
	{Name: "create_issue", Description: "Create a new issue"},
}

var writeOnlyTools = []McpTool{
	{Name: "create_record", Description: "Create a record"},
	{Name: "update_record", Description: "Update a record"},
	{Name: "delete_record", Description: "Delete a record"},
}

func TestGenerateProfileGranular(t *testing.T) {
	t.Run("json_extract when list tools detected", func(t *testing.T) {
		s := generateProfile("jira", listTools)
		for _, want := range []string{`type = "json_extract"`, "items_path", "fields"} {
			if !strings.Contains(s, want) {
				t.Errorf("missing %q", want)
			}
		}
	})
	t.Run("json_truncate when no list tools", func(t *testing.T) {
		s := generateProfile("myservice", writeOnlyTools)
		if !strings.Contains(s, "json_truncate") || strings.Contains(s, "items_path") {
			t.Errorf("got:\n%s", s)
		}
	})
	t.Run("id uses server key with underscores", func(t *testing.T) {
		s := generateProfile("my-jira", listTools)
		if !strings.Contains(s, `id          = "mcp__my_jira"`) || !strings.Contains(s, `mcp_pattern = "mcp__my_jira__*"`) {
			t.Errorf("got:\n%s", s)
		}
	})
	t.Run("id normalizes hyphens", func(t *testing.T) {
		if s := generateProfile("some-service", writeOnlyTools); !strings.Contains(s, `"mcp__some_service"`) {
			t.Errorf("got:\n%s", s)
		}
	})
	t.Run("includes generator comment", func(t *testing.T) {
		if s := generateProfile("jira", listTools); !strings.Contains(s, "# Generated by: mcp-recall learn") {
			t.Error("missing generator comment")
		}
	})
	t.Run("includes detected list tools in comment", func(t *testing.T) {
		s := generateProfile("jira", listTools)
		if !strings.Contains(s, "list_issues") || !strings.Contains(s, "search_issues") {
			t.Errorf("got:\n%s", s)
		}
	})
	t.Run("includes common fields in json_extract", func(t *testing.T) {
		s := generateProfile("jira", listTools)
		for _, want := range []string{`"id"`, `"title"`, `"status"`} {
			if !strings.Contains(s, want) {
				t.Errorf("missing %q", want)
			}
		}
	})
	t.Run("suggests issue-related items_path for jira", func(t *testing.T) {
		if s := generateProfile("jira", listTools); !strings.Contains(s, `"issues"`) {
			t.Error("missing issues items_path")
		}
	})
	t.Run("json_extract TOML is parseable", func(t *testing.T) {
		var v map[string]any
		if _, err := toml.Decode(generateProfile("jira", listTools), &v); err != nil {
			t.Errorf("parse error: %v", err)
		}
	})
	t.Run("json_truncate TOML is parseable", func(t *testing.T) {
		var v map[string]any
		if _, err := toml.Decode(generateProfile("myservice", writeOnlyTools), &v); err != nil {
			t.Errorf("parse error: %v", err)
		}
	})
	t.Run("handles empty tool list", func(t *testing.T) {
		if s := generateProfile("empty", []McpTool{}); !strings.Contains(s, "json_truncate") {
			t.Errorf("empty → should be json_truncate:\n%s", s)
		}
	})
}
